research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information.
  expected_output: >
    A list containing the disease, possible causes, medication and prevention techniques related to {topic}.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A Full fledge Medical Report from the context you got, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

# file_writing_task:
#   description: >
#     Write a Medical report to a file
#   expected_output: >
#     A brief Medical Report about the information recieved in the previous task into a file named Reports\med_report.md
#   agent: file_writer
